# Generated by Django 6.0.2 on 2026-03-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
