# Generated by Django 6.0.2 on 2026-03-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmeta_options_alter_reply_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
