# Generated by Django 6.0.2 on 2026-03-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_focus_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('info', 'Informative (BlogPosting)'), ('review', 'Product Review (Review)')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_name',
            field=models.CharField(blank=True, help_text='রিভিউ পোস্ট হলে প্রোডাক্টের নাম দিন', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='প্রোডাক্টের দাম (USD)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_url',
            field=models.URLField(blank=True, help_text='অ্যাফিলিয়েট বা প্রোডাক্ট লিংক', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='rating_value',
            field=models.FloatField(blank=True, default=4.5, help_text='রেটিং (১ থেকে ৫ এর মধ্যে)', null=True),
        ),
    ]
