# Generated by Django 6.0.2 on 2026-03-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_post_type_blogpost_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='product_url',
            field=models.URLField(blank=True, help_text='অ্যাফিলিয়েট বা প্রোডাক্ট লিংক', null=True),
        ),
    ]
