# Generated by Django 6.0.2 on 2026-03-27 05:37

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(blank=True, help_text='Type your full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_user.png', null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
