# Generated by Django 6.0.2 on 2026-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_author_full_name_alter_author_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default_user.png', null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
