# Generated by Django 6.0.2 on 2026-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_emailchangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, default='upload/user_defult.jpeg', null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='upload/user_defult.jpeg', upload_to='profile_pics'),
        ),
    ]
