# Generated by Django 6.0.2 on 2026-04-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_staticpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Static Page', 'verbose_name_plural': 'Static Pages'},
        ),
        migrations.AddField(
            model_name='staticpage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='পেইজটি কোন সিরিয়ালে থাকবে (যেমন: ১, ২, ৩)'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(blank=True, help_text='উদা: about-us, privacy-policy', unique=True),
        ),
    ]
