# Generated by Django 6.0.2 on 2026-04-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='created_at',
            new_name='subscribed_at',
        ),
    ]
