"""
Django settings for blogsite project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# ১. Build paths (এটি ডিফল্টভাবে থাকে)
BASE_DIR = Path(__file__).resolve().parent.parent

# ২. .env ফাইল লোড করা (একবারই যথেষ্ট এবং পাথ বলে দেওয়া ভালো)
load_dotenv(os.path.join(BASE_DIR, '.env'))

# ৩. ভেরিয়েবলগুলো ব্যবহার করা
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# ৪. CKEditor কনফিগারেশন ইম্পোর্ট
try:
    from .ckeditor_config import *
except ImportError:
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # ১. ইউজার ইন্টারফেস এবং থিম (সবসময় সবার উপরে থাকে)
    "jazzmin",

# ২. ডিফল্ট জ্যাঙ্গো অ্যাপস
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",# Dynamic XML Sitemap
    "django.contrib.sites", # এটি অল-অথ এবং সাইটম্যাপের জন্য জরুরি


    # ৩. থার্ড পার্টি লাইব্রেরি (ইউটিলিটি)
    "django_cleanup.apps.CleanupConfig",
    "django_ckeditor_5",
    "taggit",
    "django_social_share",

    # ৪. Django-Allauth (অ্যাকাউন্ট ম্যানেজমেন্ট)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # ৫. ব্যাকগ্রাউন্ড টাস্ক প্রসেসর
    'django_q',

    # ৭. সিগন্যাল কানেক্টর (অ্যাপ কনফিগারেশনে উল্লেখ করা হয়েছে)
    'blog.apps.BlogConfig',

    # ৬. আপনার অ্যাপ্লিকেশন
    #"blog",
    'crispy_forms',
    'crispy_bootstrap5',
]


SITE_ID = 1 # Dynamic XML Sitemap

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = "blogsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # আপনার প্রসেসরটি এখানে যোগ করুন
                'blog.context_processors.global_categories',
                'django.template.context_processors.request',
                'blog.context_processors.footer_pages',
            ],
        },
    },
]

WSGI_APPLICATION = "blogsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dhaka" # বাংলাদেশের টাইমজোন

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# CKEditor 5 settings
CKEDITOR_5_UPLOAD_PATH = "uploads/ckeditor5/"
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# tags
TAGGIT_CASE_INSENSITIVE = True


# লগ-ইন করার পর ইউজারকে হোম পেজে নিয়ে যাবে
LOGIN_REDIRECT_URL = "home"

# লগ-আউট করার পরও ইউজারকে লগিন পেজে নিয়ে যাবে
LOGOUT_REDIRECT_URL = "login"






# --- Email Configuration (Gmail SMTP) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Load from .env for security
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Dynamic Sender Email
DEFAULT_FROM_EMAIL = f"Forest Time <{EMAIL_HOST_USER}>"
# --- End Email Configuration ---



# JAZZMIN Admin Panel (সংশোধিত)
JAZZMIN_SETTINGS = {
    "site_title": "My Admin",
    "site_header": "My Blog Admin",
    "site_brand": "My Blog",
    "welcome_sign": "Welcome to the Blog Admin",
    "copyright": "My Blog Ltd",
    "show_sidebar": True,
    "navigation_expanded": True,
    
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # ১. এখানে ওপরের মেনুতে অ্যানালিটিক্স লিঙ্ক যুক্ত হলো
        {"name": "Analytics", "url": "admin:full_analytics", "icon": "fas fa-chart-line"},
        {"name": "Website", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],

    # ২. বামের সাইডবারে "Custom Links" সেকশনে লিঙ্কটি দেখানোর জন্য এটি যোগ করুন
    "custom_links": {
        "blog": [ # আপনার অ্যাপের নাম 'blog' হলে এখানে তার নিচে দেখাবে
            {
                "name": "Live Analytics", 
                "url": "admin:full_analytics", 
                "icon": "fas fa-chart-bar",
                "permissions": ["auth.view_group"]
            },
        ],
    },

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "blog": "fas fa-newspaper",
        "blog.BlogPost": "fas fa-file-alt",
        "blog.Category": "fas fa-list",
        "blog.Author": "fas fa-user-tie",
        "blog.Comment": "fas fa-comments",
    },
    
    "order_with_respect_to": [
        "blog",
        "blog.BlogPost",
        "blog.Category",
        "blog.Author",
    ],
}

# ১. অথেন্টিকেশন ব্যাকেন্ডস
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ২. ইমেইল ভেরিফিকেশন সেটিংস
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # ইমেইল ভেরিফাই করা বাধ্যতামূলক
ACCOUNT_LOGIN_METHODS = {'email'}         # ইমেইল দিয়ে লগইন করতে হবে

# ৩. সাইন-আপ ফিল্ড কনফিগারেশন (নতুন স্ট্যান্ডার্ড)
# এটি ব্যবহার করলে আলাদাভাবে EMAIL_REQUIRED বা PASSWORD_ENTER_TWICE প্রয়োজন নেই
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# ৪. অতিরিক্ত সেটিংস (প্রয়োজন হলে)
ACCOUNT_LOGOUT_ON_GET = True              # লিঙ্কে ক্লিক করলেই লগআউট হবে (কনফার্মেশন পেজ আসবে না)
ACCOUNT_UNIQUE_EMAIL = True               # একটি ইমেইল একবারই ব্যবহার করা যাবে

# Crispy Forms সেটিংস
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"



# ৩. Django-Q2 সেটিংস (ওআরএম ব্রোকার হিসেবে)
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,
    'timeout': 90,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default', # আলাদা কোনো Redis লাগবে না, ডাটাবেজ ব্যবহার করবে
}

# Django-Q2 এর জন্য কাস্টম অ্যাকাউন্ট অ্যাডাপ্টার সেটিং
ACCOUNT_ADAPTER = 'blog.adapters.MyAccountAdapter'

