"""
Django settings for blogsite project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path
# ckeditor_config.py ফাইল থাকলে এখান থেকে ইম্পোর্ট হবে
try:
    from .ckeditor_config import *
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8cg$tw(e$+#!$0ew0h^!vaxrd^lfdktpuku!v7zd13c!)*4jex"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin", 
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "blog",
    "django_ckeditor_5",
    "taggit",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "blogsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # আপনার প্রসেসরটি এখানে যোগ করুন
                "blog.context_processors.category_context",
            ],
        },
    },
]

WSGI_APPLICATION = "blogsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dhaka" # বাংলাদেশের টাইমজোন

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# CKEditor 5 settings
CKEDITOR_5_UPLOAD_PATH = "uploads/ckeditor5/"
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# tags
TAGGIT_CASE_INSENSITIVE = True


# লগ-ইন করার পর ইউজারকে হোম পেজে নিয়ে যাবে
LOGIN_REDIRECT_URL = "home"

# লগ-আউট করার পরও ইউজারকে লগিন পেজে নিয়ে যাবে
LOGOUT_REDIRECT_URL = "login"


# SMTP Server Config
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp-relay.brevo.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "আপনার_ইমেইল"
EMAIL_HOST_PASSWORD = "আপনার_পাসওয়ার্ড"

# JAZZMIN Admin Panel (সবগুলো সেটিংসকে একটি ডিকশনারিতে মার্জ করা হয়েছে)
JAZZMIN_SETTINGS = {
    "site_title": "My Admin",
    "site_header": "My Blog Admin",
    "site_brand": "My Blog",
    # "site_logo": "img/logo.png", # ফাইল থাকলে আন-কমেন্ট করুন
    "welcome_sign": "Welcome to the Blog Admin",
    "copyright": "My Blog Ltd",
    "show_sidebar": True,
    "navigation_expanded": True,
    
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Website", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "blog": "fas fa-newspaper",
        "blog.BlogPost": "fas fa-file-alt",
        "blog.Category": "fas fa-list",
        "blog.Author": "fas fa-user-tie",
        "blog.Comment": "fas fa-comments",
    },
    
    "order_with_respect_to": [
        "blog",
        "blog.BlogPost",
        "blog.Category",
        "blog.Author",
    ],
}